In [1]:
import pandas as pd
from ip_to_geo_1 import ip_to_geo
import json
from util import *

In [10]:
df = pd.read_excel('F20 Grades.xlsx')

In [17]:
df['name'] = df['Pr√©nom'] + ' ' + df['Nom']

In [19]:
num = 0
for i, row in df.iterrows():
    num+=1
print(num)

248

In [22]:
sorted_df = df.sort_values('Grade', ascending=False)

In [49]:
num = 0
for i, row in sorted_df.iterrows():
    num += 1
    print(row['Grade'])
    if num == 83 or num == 166:
        print('#################################################################')

82.05
77.05833333333332
76.25
75.95
74.625
74.15833333333333
71.27499999999999
70.95833333333333
70.7
69.78333333333333
69.13333333333334
67.325
66.3
65.9
65.15833333333333
65.125
64.30833333333334
64.23333333333333
64.23333333333333
63.55833333333333
63.25833333333334
63.125
62.80833333333333
62.583333333333336
61.80833333333333
61.53333333333333
61.40833333333333
61.30833333333334
61.099999999999994
60.7
60.55833333333334
60.15833333333333
59.625
59.58333333333334
59.50833333333334
59.375
58.75
58.625
58.3
58.3
58.125
57.8
57.78333333333333
57.733333333333334
57.60833333333334
57.575
57.52499999999999
57.400000000000006
57.2
57.05
56.88333333333333
56.875
56.85000000000001
56.78333333333333
56.65833333333333
56.60833333333333
56.55
56.483333333333334
56.325
56.2
56.2
56.03333333333333
55.8
55.78333333333333
55.7
55.575
55.45
55.358333333333334
55.15833333333333
55.125
55.075
54.88333333333333
54.88333333333333
54.875
54.7
54.525
54.50833333333334
54.50833333333334
54.13333333333334
53.983333333333334
53.825
53.708333333333336
53.358333333333334
#################################################################
53.083333333333336
52.925000000000004
52.9
52.40833333333334
51.95
51.80833333333334
51.60833333333333
51.55833333333334
51.45833333333334
50.8
50.75
50.7
50.53333333333334
50.30833333333334
50.275
50.13333333333334
50.008333333333326
49.900000000000006
49.825
49.50833333333334
49.425
49.23333333333333
49.224999999999994
49.008333333333326
48.55833333333333
48.18333333333334
48.03333333333334
47.983333333333334
47.974999999999994
47.95
47.758333333333326
47.58333333333333
47.50833333333333
47.43333333333333
47.28333333333333
46.89999999999999
46.7
46.625
46.483333333333334
46.43333333333332
46.083333333333336
46.050000000000004
45.975
45.78333333333333
45.63333333333333
45.525000000000006
45.28333333333333
45.108333333333334
45.08333333333333
44.858333333333334
44.625
44.50833333333334
44.45833333333333
44.38333333333333
44.3
43.75
43.63333333333333
43.383333333333326
43.075
43.05833333333334
42.95
42.85
42.70833333333334
42.68333333333334
42.55833333333334
42.52499999999999
42.45
42.333333333333336
42.28333333333333
42.108333333333334
41.983333333333334
41.95
41.90833333333333
41.508333333333326
41.358333333333334
41.15833333333334
41.13333333333333
40.45
40.233333333333334
40.15
40.13333333333334
39.95833333333333
39.775
#################################################################
39.58333333333333
39.50833333333334
39.5
39.300000000000004
39.05833333333333
39.025000000000006
38.95833333333333
38.575
38.15
38.125
38.0
37.93333333333334
37.40833333333334
37.3
37.125
37.05
36.95833333333333
36.708333333333336
36.7
36.375
36.275
36.1
36.05
36.0
35.875
35.358333333333334
35.00833333333333
34.5
34.35
34.25833333333333
33.90833333333333
33.88333333333334
33.7
33.4
33.20833333333333
33.18333333333334
33.05833333333333
32.925
32.925
32.825
32.758333333333326
32.425000000000004
32.333333333333336
32.3
32.175
32.125
31.53333333333333
31.375
31.125
30.83333333333333
30.658333333333335
29.38333333333333
28.275000000000002
28.25
27.475
26.133333333333333
25.75
24.675000000000004
24.383333333333333
23.325
22.78333333333333
22.650000000000002
20.90833333333333
20.75
19.875
19.633333333333333
19.625
17.35
14.383333333333335
14.299999999999999
14.225000000000001
13.75
13.75
10.633333333333333
9.883333333333333
9.383333333333333
7.25
5.4
0.0
0.0
0.0
0.0

In [31]:
n = 0
op = []
p = 'Good'
for i, row in sorted_df.iterrows():
    name = row['name']
    grade = row['Grade']
    n += 1
    op.append({'User full name': name, 'Grade': grade, 'Performance': p})
    if n == 83:
        p = 'Fair'
    if n == 166:
        p = 'Poor'

In [43]:
df_out = pd.DataFrame(op)
df_out.to_csv('./performance_F20.csv', mode = 'w', index = False, header = True, encoding='utf-8-sig')

In [52]:
n = 0
op = []
p = 'Passed'
for i, row in sorted_df.iterrows():
    name = row['name']
    grade = row['Grade']
    n += 1
    op.append({'User full name': name, 'Grade': grade, 'Performance': p})
    if n == 100:
        p = 'Failed'

In [54]:
df_out = pd.DataFrame(op)
df_out.to_csv('./performance_pf_F20.csv', mode = 'w', index = False, header = True, encoding='utf-8-sig')